contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #rnaseqy channel"
    url: https://nfcore.slack.com/channels/rnaseqy
    about: Discussion about the nf-core/rnaseqy pipeline
